# Generated by Django 5.0.1 on 2024-02-12 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=50)),
                ('contra', models.CharField(max_length=100)),
                ('rol', models.CharField(max_length=20, null=True)),
                ('tel', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=100)),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
    ]
